# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

# https://adamj.eu/tech/2021/09/16/introducing-django-upgrade/#with-pre-commit
-   repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8

default_language_version:
    python: python3.8

exclude: '/static/|/tests/|/migrations/'
