# Generated by Django 4.1.7 on 2023-03-08 13:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=150, verbose_name='Apellidos')),
                ('profession', models.CharField(max_length=50, verbose_name='Profesión')),
                ('city', models.CharField(max_length=50, verbose_name='Localidad')),
                ('comment', models.TextField(verbose_name='Comentarios')),
                ('image', models.ImageField(upload_to='images', verbose_name='Foto')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
            ],
        ),
    ]
