# Generated by Django 4.1.7 on 2023-03-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canalroya', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='email',
            field=models.EmailField(default='without-email@salvemoscanalroya.org', max_length=254, verbose_name='Correo electrónico'),
            preserve_default=False,
        ),
    ]
