# Generated by Django 4.1.7 on 2023-03-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canalroya', '0002_testimonial_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Spam'), (4, 'Trash'), (5, 'Incomplete')], default=1),
        ),
    ]
