# Generated by Django 4.1.7 on 2023-03-23 10:55

from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canalroya', '0004_alter_testimonial_image_alter_testimonial_status'),
    ]

    operations = [
        TrigramExtension(),
        UnaccentExtension(),
    ]
